// plugin/frameworks/vue/components/Message.vue
<template>
  <p
    :style="{
      backgroundColor: 'lightgray',
      margin: 0,
      padding: `${variables.smallSpace}px`,
      borderRadius: `${variables.borderRadius}px`,
      fontSize: `${variables.fontSize}px`,
      fontFamily: variables.fontFamily,
      ...style,
    }"
  >
    <slot />
  </p>
</template>

<script>
export default {
  props: {
    style: Object,
    variables: Object,
  },
}
</script>

// plugin/frameworks/svelte/components/Message.svelte
<script>
  export let variables;
  export let style = '';
</script>

<p style="background-color: lightgray; margin: 0; padding: {variables.smallSpace}px; border-radius: {variables.borderRadius}px; font-size: {variables.fontSize}; font-family: {variables.fontFamily}; {style}" {...$$restProps}>
    <slot />
</p>
