// plugin/frameworks/vue/components/Tab.vue
<template>
  <button
    type="button"
    :style="{
      cursor: 'pointer',
      color: variables.color,
      background: 'none',
      border: 'none',
      outline: 'none',
      padding: 0,
      fontSize: `${variables.fontSize}px`,
      fontFamily: variables.fontFamily,
      fontWeight: active ? 'bold' : 'normal',
      ...style,
    }"
  >
    <slot />
  </button>
</template>

<script>
export default {
  props: {
    style: Object,
    variables: Object,
    active: {
      type: Boolean,
      default: false,
    },
  },
}
</script>

// plugin/frameworks/svelte/components/Tab.svelte
<script>
  export let style
  export let variables
  export let active = false
</script>

<button
  type="button"
  style="cursor: pointer; background: none; outline: none; border: none; padding: 0; color: {variables.color}; font-size: {variables.fontSize}px; font-family: {variables.fontFamily}; font-weight: {active
    ? 'bold'
    : 'normal'};"
  on:click
  {...$$restProps}
>
  <slot />
</button>
