// plugin/frameworks/base/Authentication.tsx
import React, { FormEvent, useCallback, useEffect, useMemo, useState } from 'react'
import {
  Label,
  Text,
  defaultVariables,
  defaultLabels,
  Store,
  configure,
  validateEmail,
  validatePhone,
  countries,
  authenticate,
  initializePolling,
  confirm,
  stopPolling,
} from 'iltio'
import { Props } from 'iltio/react'
import { Phone } from './Phone'
import { components } from './Components'
import { Tabs } from './Tabs'
import { Code } from './Code'

export function Authentication({
  allowPhone = true,
  allowMail = true,
  onSuccess,
  initialCountryCode = 'us',
  style = {},
  variables = defaultVariables,
  labels = {},
  Components = components,
  configuration = {},
}: Props) {
  const [tab, setTab] = useState(allowMail ? 'mail' : 'phone')
  const [mail, setMail] = useState('')
  const [phone, setPhone] = useState('')
  const [countryCode, setCountryCode] = useState(initialCountryCode.toLowerCase())
  const [mailValid, setMailValid] = useState(true)
  const [phoneValid, setPhoneValid] = useState(true)
  const multipleInputs = allowMail && allowPhone
  const [loading, setLoading] = useState(false)
  const [submitted, setSubmitted] = useState(Store.codeToken !== '')
  const [registration, setRegistration] = useState(false)
  const [error, setError] = useState('')
  const [codeValid, setCodeValid] = useState(true)

  Components = useMemo(() => ({ ...components, ...Components }), [Components])
  variables = useMemo(() => ({ ...defaultVariables, ...variables }), [variables])
  labels = useMemo(() => ({ ...defaultLabels, ...labels }), [labels])
  style = { phoneCountry: {}, phoneCountryOption: {}, ...style }

  const handleSubmit = useCallback(
    async (event: FormEvent<HTMLButtonElement>) => {
      event.preventDefault()
      setError('')
      let name: string

      if (tab === 'mail' && allowMail) {
        const currentMailValid = validateEmail(mail)
        setMailValid(currentMailValid)
        if (!currentMailValid) {
          setError(Text.InvalidMailError)
          return
        }
        name = mail
      }

      if (tab === 'phone' && allowPhone) {
        const removeLeadingZeros = String(Number(phone))
        const fullPhone = countries[countryCode].prefix + removeLeadingZeros
        const currentPhoneValid = validatePhone(fullPhone)
        setPhoneValid(currentPhoneValid)
        if (!currentPhoneValid) {
          setError(Text.InvalidPhoneNumberError)
          return
        }
        name = fullPhone
      }

      setLoading(true)

      const {
        codeToken,
        error: localError,
        registration: localRegistration,
      } = await authenticate(name)

      if (codeToken) {
        Store.codeToken = codeToken
        Store.name = name
      }

      setLoading(false)

      if (localError) {
        setError(localError === true ? Text.UnknownError : localError)
        return
      }

      setRegistration(localRegistration)
      setSubmitted(true)
    },
    [mail, phone, allowMail, allowPhone, tab]
  )

  const handleCode = useCallback(
    async (code: string) => {
      if (code.length === 4) {
        setError('')
        const { error: localError, token: userToken } = await confirm(code)

        if (localError) {
          if (localError === 'Code invalid or expired.') {
            Store.removeCodeToken()
            setSubmitted(false)
            setError(Text.CodeExpiredError)
          }

          if (localError === 'Wrong code entered.') {
            setCodeValid(false)
          }
          return
        }

        stopPolling()

        if (userToken) {
          Store.token = userToken
          Store.removeCodeToken()
          if (onSuccess) {
            onSuccess(Store.name, userToken, registration)
          }
        }
      } else {
        setCodeValid(true)
      }
    },
    [registration]
  )

  useEffect(() => {
    initializePolling(
      onSuccess,
      () => {
        setSubmitted(false)
        setError(Text.CodeExpiredError)
      },
      registration
    )

    if (configuration) {
      configure(configuration)
    }
  }, [registration, configuration, onSuccess, submitted]) // submitted necessary!

  return (
    <Components.Form
      aria-label={Label.form}
      onSubmit={handleSubmit}
      style={style.form}
      variables={variables}
    >
      {!submitted && (
        <>
          <Tabs
            multipleInputs={multipleInputs}
            tab={tab}
            Components={Components}
            setTab={setTab}
            style={style}
            variables={variables}
            labels={labels}
          />
          {allowMail && (!multipleInputs || tab === 'mail') && (
            <Components.Input
              aria-label={Label.inputMail}
              aria-invalid={!mailValid}
              value={mail}
              onChange={(event) => setMail(event.target.value)}
              required
              valid={mailValid}
              variables={variables}
              style={style.inputMail}
              placeholder={Text.MailInputPlaceholder}
              type="email"
            />
          )}
          {allowPhone && (!multipleInputs || tab === 'phone') && (
            <Phone
              variables={variables}
              phoneValid={phoneValid}
              countryCode={countryCode}
              setCountryCode={setCountryCode}
              phone={phone}
              setPhone={setPhone}
              Components={Components}
              style={style}
            />
          )}
          {error && (
            <Components.Error
              aria-label={Label.inputError}
              style={style.error}
              variables={variables}
            >
              {error}
            </Components.Error>
          )}
          <Components.Button
            aria-label={Label.submit}
            onClick={handleSubmit}
            type="submit"
            style={style.button}
            variables={variables}
          >
            {loading ? Text.LoadingButton : labels.submit}
          </Components.Button>
        </>
      )}
      {submitted && (
        <Code
          Components={Components}
          style={style}
          variables={variables}
          labels={labels}
          registration={registration}
          codeValid={codeValid}
          handleCode={handleCode}
        />
      )}
    </Components.Form>
  )
}

// plugin/frameworks/vue/Authentication.vue
<template>
  <Form
    :aria-label="Label.form"
    @submit.prevent="handleSubmit"
    :style="style.form"
    :variables="variables"
  >
    <template v-if="!submitted">
      <Tabs
        :multipleInputs="multipleInputs"
        :tab="tab"
        :setTab="setTab"
        :style="style"
        :variables="variables"
        :labels="labels"
      />
      <Input
        v-if="allowMail && (!multipleInputs || tab === 'mail')"
        :aria-label="Label.inputMail"
        :aria-invalid="!mailValid"
        :value="mail"
        @input="(event) => setMail(event.target.value)"
        required
        :valid="mailValid"
        :variables="variables"
        :style="style.inputMail"
        :placeholder="Text.MailInputPlaceholder"
        type="email"
      />
      <Phone
        v-if="allowPhone && (!multipleInputs || tab === 'phone')"
        :variables="variables"
        :phoneValid="phoneValid"
        :countryCode="countryCode"
        :setCountryCode="setCountryCode"
        :phone="phone"
        :setPhone="setPhone"
        :style="style"
      />
      <Error
        v-if="error"
        :style="style.error"
        :variables="variables"
        :aria-label="Label.inputError"
      >
        {{ error }}
      </Error>
      <Button :aria-label="Label.submit" type="submit" :style="style.button" :variables="variables">
        {{ loading ? Text.LoadingButton : labels.submit }}
      </Button>
    </template>
    <template v-else>
      <Code
        :style="style"
        :variables="variables"
        :labels="labels"
        :registration="registration"
        :codeValid="codeValid"
        :handleCode="handleCode"
      />
    </template>
  </Form>
</template>

<script>
import {
  Label,
  Text,
  defaultVariables,
  defaultLabels,
  Store,
  countries,
  validateEmail,
  validatePhone,
  authenticate,
  configure,
  initializePolling,
  confirm,
  app,
} from 'iltio'
import Phone from './Phone.vue'
import Tabs from './Tabs.vue'
import Code from './Code.vue'
import Form from './components/Form.vue'
import Input from './components/Input.vue'
import Button from './components/Button.vue'
import Error from './components/Error.vue'

export default {
  props: {
    configuration: Object,
    allowPhone: { type: Boolean, default: true },
    allowMail: { type: Boolean, default: true },
    initialCountryCode: { type: String, default: 'us' },
    style: { type: Object, default: () => ({ phoneCountry: {}, phoneCountryOption: {} }) },
    variables: { type: Object, default: () => defaultVariables },
    labels: { type: Object, default: () => ({ ...defaultLabels }) },
    onSuccess: { type: Function, required: true },
  },
  data() {
    return {
      tab: this.allowMail ? 'mail' : 'phone',
      mail: '',
      phone: '',
      countryCode: this.initialCountryCode.toLowerCase(),
      mailValid: true,
      phoneValid: true,
      multipleInputs: this.allowMail && this.allowPhone,
      loading: false,
      submitted: Store.codeToken !== '',
      registration: false,
      error: '',
      codeValid: true,
      Text,
      Label,
    }
  },
  components: {
    Tabs,
    Code,
    Phone,
    Form,
    Input,
    Button,
    Error,
  },
  methods: {
    async handleSubmit() {
      this.error = ''
      let name

      if (this.tab === 'mail' && this.allowMail) {
        const currentMailValid = validateEmail(this.mail)
        this.mailValid = currentMailValid
        if (!currentMailValid) {
          this.error = Text.InvalidMailError
          return
        }
        name = this.mail
      }

      if (this.tab === 'phone' && this.allowPhone) {
        const removeLeadingZeros = String(Number(this.phone))
        const fullPhone = countries[this.countryCode].prefix + removeLeadingZeros
        const currentPhoneValid = validatePhone(fullPhone)
        this.phoneValid = currentPhoneValid
        if (!currentPhoneValid) {
          this.error = Text.InvalidPhoneNumberError
          return
        }
        name = fullPhone
      }

      this.loading = true

      const {
        codeToken,
        error: localError,
        registration: localRegistration,
      } = await authenticate(name)

      if (codeToken) {
        Store.codeToken = codeToken
        Store.name = name
      }

      this.loading = false

      if (localError) {
        this.error = localError === true ? Text.UnknownError : localError
        return
      }

      this.registration = localRegistration
      this.submitted = true

      initializePolling(
        this.onSuccess,
        () => {
          this.submitted = false
          this.error = Text.CodeExpiredError
        },
        this.registration
      )
    },
    async handleCode(code) {
      if (code.length === 4) {
        this.error = ''
        const { error: localError, token: userToken } = await confirm(code)

        if (localError) {
          if (localError === 'Code invalid or expired.') {
            Store.removeCodeToken()
            this.submitted = false
            this.error = Text.CodeExpiredError
          }

          if (localError === 'Wrong code entered.') {
            this.codeValid = false
          }
          return
        }

        if (app.pollInterval) {
          clearInterval(app.pollInterval)
          app.pollInterval = 0
        }

        if (userToken) {
          Store.token = userToken
          Store.removeCodeToken()
          if (this.onSuccess) {
            this.onSuccess(Store.name, userToken, this.registration)
          }
        }
      } else {
        this.codeValid = true
      }
    },
    setTab(value) {
      this.tab = value
    },
    setCountryCode(value) {
      this.countryCode = value
    },
    setPhone(value) {
      this.phone = value
    },
    setMail(value) {
      this.mail = value
    },
  },
  mounted() {
    initializePolling(
      this.onSuccess,
      () => {
        this.submitted = false
        this.error = Text.CodeExpiredError
      },
      this.registration
    )

    if (this.configuration) {
      configure(this.configuration)
    }
  },
}
</script>
