// plugin/frameworks/svelte/components/Button.svelte
<script>
  export let variables
  export let style = ''
</script>

<button
  on:click
  type="submit"
  style="background-color: {variables.color}; border: none; color: {variables.contrast}; padding: {variables.smallSpace}px; cursor: pointer; border-radius: {variables.borderRadius}; font-size: {variables.fontSize}; font-family: {variables.fontFamily}; {style}"
  {...$$restProps}
>
  <slot />
</button>

// plugin/frameworks/vue/components/Button.vue
<template>
  <button
    :style="{
      backgroundColor: variables.color,
      border: 'none',
      color: variables.contrast,
      // TODO use toPx helper.
      padding: `${variables.smallSpace}px`,
      cursor: 'pointer',
      borderRadius: variables.borderRadius,
      fontSize: `${variables.fontSize}px`,
      fontFamily: variables.fontFamily,
      ...style,
    }"
  >
    <slot />
  </button>
</template>

<script>
export default {
  props: {
    variables: {
      type: Object,
      required: true,
    },
    style: {
      type: Object,
      default: () => ({}),
    },
    children: {
      type: [String, Number],
    },
  },
}
</script>
