// plugin/frameworks/svelte/components/Input.svelte
<script>
  export let variables
  export let valid = true
  export let style = ''
</script>

<input
  on:input
  style="border-width: 1px; border-style: solid; border-color: {valid
    ? variables.color
    : 'red'}; padding: 9px; outline: none; border-radius: {variables.borderRadius}px; font-size: {variables.fontSize}px; font-family: {variables.fontFamily}; background-color: inherit; {style}"
  {...$$restProps}
/>

// plugin/frameworks/vue/components/Input.vue
<template>
  <input
    :style="{
      borderWidth: '1px',
      borderStyle: 'solid',
      borderColor: valid ? variables.color : 'red',
      padding: '9px',
      outline: 'none',
      borderRadius: `${variables.borderRadius}px`,
      fontSize: `${variables.fontSize}px`,
      fontFamily: variables.fontFamily,
      backgroundColor: 'inherit',
      ...style,
    }"
  />
</template>

<script>
export default {
  props: {
    variables: Object,
    valid: Boolean,
    style: Object,
  },
}
</script>
