// plugin/frameworks/svelte/components/PhoneWrapper.svelte
<script>
  export let variables
  export let style = ''
  export let valid = true
</script>

<div
  style="display: flex; flex-direction: column; border: 1px solid {valid
    ? variables.color
    : 'red'}; border-radius: {variables.borderRadius}px; padding-left: {variables.smallSpace}px; {style}"
  {...$$restProps}
>
  <slot />
</div>

// plugin/frameworks/vue/components/PhoneWrapper.vue
<template>
  <div
    :style="{
      display: 'flex',
      flexDirection: 'column',
      borderWidth: '1px',
      borderStyle: 'solid',
      borderColor: valid ? variables.color : 'red',
      borderRadius: `${variables.borderRadius}px`,
      paddingLeft: `${variables.smallSpace}px`,
      ...style,
    }"
  >
    <slot />
  </div>
</template>

<script>
export default {
  props: {
    style: Object,
    variables: Object,
    valid: {
      type: Boolean,
      default: true,
    },
  },
}
</script>
