// plugin/frameworks/svelte/components/PhoneCountryOptions.svelte
<script>
  export let variables
  export let style = ''
</script>

<div
  style="display: flex; flex-direction: column; max-height: 200px; overflow-y: auto; overflow-x: hidden; padding-right: {variables.smallSpace}px; padding-bottom: {variables.smallSpace}px; row-gap: 5px; {style}"
  {...$$restProps}
>
  <slot />
</div>

// plugin/frameworks/vue/components/PhoneCountryOptions.vue
<template>
  <div
    :style="{
      display: 'flex',
      flexDirection: 'column',
      maxHeight: '200px',
      overflowY: 'auto',
      overflowX: 'hidden',
      paddingRight: `${variables.smallSpace}px`,
      paddingBottom: `${variables.smallSpace}px`,
      rowGap: '5px',
      ...style,
    }"
  >
    <slot />
  </div>
</template>

<script>
export default {
  props: {
    style: Object,
    variables: Object,
  },
}
</script>
