// plugin/frameworks/svelte/components/PhoneInput.svelte
<script>
  export let variables
  export let valid = true
  export let style = ''
</script>

<input
  on:input
  style="border: none; border-color: {valid
    ? variables.color
    : variables.colorError}; padding: 9px; width: 100%; outline: none; font-size: {variables.fontSize}px; font-family: {variables.fontFamily}; background: none; {style}"
  {...$$restProps}
/>

// plugin/frameworks/vue/components/PhoneInput.vue
<template>
  <input
    :style="{
      background: 'none',
      border: 'none',
      padding: '9px',
      outline: 'none',
      width: '100%',
      borderColor: valid ? variables.color : variables.colorError,
      fontSize: `${variables.fontSize}px`,
      fontFamily: variables.fontFamily,
      ...style,
    }"
  />
</template>

<script>
export default {
  props: {
    style: Object,
    variables: Object,
    valid: {
      type: Boolean,
      default: true,
    },
  },
}
</script>
