// plugin/frameworks/solid/Resend.jsx
import { createSignal } from 'solid-js'
import { Label, resend } from 'iltio'

export function Resend(props) {
  const [loading, setLoading] = createSignal(false)
  const [error, setError] = createSignal('')

  const handleReset = async () => {
    setLoading(true)
    setError('')

    const { error: localError } = await resend()

    if (localError) {
      setError(typeof localError === 'string' ? localError : 'An error occurred.')
    }

    setLoading(false)
  }

  return (
    <>
      <props.Components.Button
        aria-label={Label.resendCode}
        onClick={handleReset}
        type="button"
        style={props.style.button}
        variables={props.variables}
      >
        {loading() ? 'Loading...' : props.labels.resend}
      </props.Components.Button>
      {error() && (
        <props.Components.Error style={props.style.error} variables={props.variables}>
          {error()}
        </props.Components.Error>
      )}
    </>
  )
}

// plugin/resend.tsx
import React, { useCallback, useState } from 'react'
import { Variables, Styles, Labels, ComponentTypes } from './types'
import { Label } from './label'
import { resend } from './route'

export function Resend({
  Components,
  style,
  variables,
  labels,
}: {
  Components: ComponentTypes
  style: Styles
  variables: Variables
  labels: Labels
}) {
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState('')

  const handleReset = useCallback(async () => {
    setLoading(true)
    setError('')

    const { error: localError } = await resend()

    if (localError) {
      setError(typeof localError === 'string' ? localError : 'An error occurred.')
    }

    setLoading(false)
  }, [])

  return (
    <>
      <Components.Button
        aria-label={Label.resendCode}
        onClick={handleReset}
        type="button"
        style={style.button}
        variables={variables}
      >
        {loading ? 'Loading...' : labels.resend}
      </Components.Button>
      {error && (
        <Components.Error style={style.error} variables={variables}>
          {error}
        </Components.Error>
      )}
    </>
  )
}
