// demo/frameworks/vue/components/MyInput.vue
<template>
  <input
    :style="{
      border: 'none',
      borderBottom: '1px solid black',
      borderColor: valid ? 'black' : 'red',
      paddingBottom: '5px',
      color: variables.color,
      cursor: 'pointer',
      outline: 'none',
      backgroundColor: 'transparent',
      ...style,
    }"
  />
</template>

<script>
export default {
  name: 'MyInput',
  props: {
    variables: Object,
    style: Object,
    valid: {
      type: Boolean,
      default: true,
    },
  },
}
</script>

// demo/frameworks/svelte/src/components/MyInput.svelte
<script>
  export let variables
  export let style
  export let valid = true
</script>

<input
  style="
      border: none;
      border-bottom: 1px solid black;
      border-color: {valid ? 'black' : 'red'};
      padding-bottom: 5px;
      color: {variables.color};
      cursor: pointer;
      outline: none;
      background-color: transparent;
      {style}
    "
  {...$$restProps}
/>
