// plugin/frameworks/solid/Phone.jsx
import { createSignal, createMemo, Show } from 'solid-js'
import { Label, countries, filterCountries } from 'iltio'

export function Phone(props) {
  const [open, setOpen] = createSignal(false)
  const [filter, setFilter] = createSignal('')
  const filteredCountries = filterCountries(filter())
  const country = createMemo(() => countries[props.countryCode()])

  return (
    <props.Components.PhoneWrapper
      style={props.style.phoneWrapper}
      variables={props.variables}
      valid={props.phoneValid}
    >
      <props.Components.PhoneTop style={props.style.phoneTop} variables={props.variables}>
        <props.Components.PhoneCountry
          prefix={country().prefix}
          flag={country().flag}
          variables={props.variables}
          togglePicker={() => setOpen(!open())}
          aria-label={Label.phoneCountry}
          data-country={props.countryCode()}
          style={props.style.phoneCountry}
        />
        <props.Components.PhoneInput
          aria-label={Label.inputPhone}
          aria-invalid={!props.phoneValid()}
          value={props.phone()}
          onInput={(event) => props.setPhone(event.currentTarget.value)}
          style={props.style.phoneInput}
          variables={props.variables}
          required
          valid={props.phoneValid}
          placeholder="Phone"
          type="tel"
        />
      </props.Components.PhoneTop>
      <Show when={open()}>
        <props.Components.PhoneCountryOptions
          style={props.style.phoneCountryOptions}
          variables={props.variables}
        >
          <props.Components.Input
            aria-label={Label.phoneInputCountrySearch}
            value={filter()}
            onInput={(event) => setFilter(event.currentTarget.value)}
            variables={props.variables}
            style={props.style.phoneInputCountrySearch}
            placeholder="Filter Countries"
            type="text"
          />
          {Object.values(filteredCountries).map((item) => (
            <props.Components.PhoneCountryOption
              aria-label={Label.phoneCountryOption}
              data-testid={item.abbreviation}
              variables={props.variables}
              selected={() => item.abbreviation === props.countryCode()}
              key={item.abbreviation}
              style={props.style.phoneCountryOption}
              onClick={() => {
                console.log('set', item.abbreviation)
                props.setCountryCode(item.abbreviation)
                setOpen(false)
              }}
            >
              {item.flag} {item.name}
            </props.Components.PhoneCountryOption>
          ))}
        </props.Components.PhoneCountryOptions>
      </Show>
    </props.Components.PhoneWrapper>
  )
}

// plugin/frameworks/base/Phone.jsx
import React, { useState } from 'react'
import { countries, Label, filterCountries } from 'iltio'

export function Phone({
  phoneValid,
  variables,
  countryCode,
  setCountryCode,
  phone,
  setPhone,
  Components,
  style,
}) {
  const [open, setOpen] = useState(false)
  const [filter, setFilter] = useState('')
  const filteredCountries = filterCountries(filter)
  const country = countries[countryCode]

  return (
    <Components.PhoneWrapper style={style.phoneWrapper} variables={variables} valid={phoneValid}>
      <Components.PhoneTop style={style.phoneTop} variables={variables}>
        <Components.PhoneCountry
          prefix={country.prefix}
          flag={country.flag}
          variables={variables}
          togglePicker={() => setOpen(!open)}
          aria-label={Label.phoneCountry}
          data-country={countryCode}
          style={style.phoneCountry}
        />
        <Components.PhoneInput
          aria-label={Label.inputPhone}
          aria-invalid={!phoneValid}
          value={phone}
          onChange={(event) => setPhone(event.target.value)}
          style={style.phoneInput}
          variables={variables}
          required
          valid={phoneValid}
          placeholder={Text.PhoneInputPlaceholder}
          type="tel"
        />
      </Components.PhoneTop>
      {open && (
        <Components.PhoneCountryOptions style={style.phoneCountryOptions} variables={variables}>
          <Components.Input
            aria-label={Label.phoneInputCountrySearch}
            value={filter}
            onChange={(event) => setFilter(event.target.value)}
            variables={variables}
            style={style.phoneInputCountrySearch}
            placeholder={Text.FilterCountriesInputPlaceholder}
            type="text"
          />
          {Object.values(filteredCountries).map((item) => (
            <Components.PhoneCountryOption
              aria-label={Label.phoneCountryOption}
              data-testid={item.abbreviation}
              variables={variables}
              selected={item.abbreviation === countryCode}
              key={item.abbreviation}
              style={style.phoneCountryOption}
              onSelect={() => {
                setCountryCode(item.abbreviation)
                setOpen(!open)
              }}
            >
              {item.flag} {item.name}
            </Components.PhoneCountryOption>
          ))}
        </Components.PhoneCountryOptions>
      )}
    </Components.PhoneWrapper>
  )
}
